### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by sgupta38** [rockNroll87q/pyDrawing#1]
There can be a provision of saving o/p as an image file.

**Comment by rockNroll87q** [comment]
Hi @sgupta38 ,

I added a code ([link](https://github.com/rockNroll87q/pyDrawing/blob/master/read_csv.py)) that read a csv created by the experiment with the list of coordinates, it converts them in lines, and save an image with drawings.
You can take a look and easily change it for your goals.
